Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,10 @@ jobs:
         - name: 🧪 Test
           run: npm run wdio
 
+        - name: Check allure-results folder
+          run: |
+            ls -la allure-results || echo "❌ allure-results folder missing!"
+
         - name: 📥 Install Allure CLI
           run: npm install -g allure-commandline --save-dev
 
